
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8000:8000"  # Adjust according to your backend server port
    environment:
      - ENV=uat       # dev won't work due to dotenv dependency
      # - ENV=prod
      - DB_NAME=tasks
    volumes:
      - backend_data:/app/data  # Mount for SQLite DB

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "80:80"  # NGINX exposes app on port 80
    depends_on:
      - backend

volumes:
  backend_data:
  
